version: "3"

volumes:
    mysql_data: {}
    mariadb_data: {}

services:
    # Add support for mysql and mariadb
    mariadb:
        container_name: mariadb_mvc
        image: mariadb:latest
        restart: always
        ports:
            - "13306:3306"
        environment:
            MARIADB_ROOT_PASSWORD: pass
        volumes:
            - mariadb_data:/var/lib/mysql
            #- ./example/sql.d/mariadb:/docker-entrypoint-initdb.d
            #- ./example/sql/inspect/mariadb_my.cnf:/root/.my.cnf
            #- ./example/sql/v2/my.cnf:/root/.my.cnf
            - .:/home

    mysql:
        container_name: mysql_mvc
        image: mysql:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "13307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: pass
        volumes:
            - mysql_data:/var/lib/mysql
            #- ./example/sql.d/mysql:/docker-entrypoint-initdb.d
            #- ./example/sql/inspect/mysql_my.cnf:/root/.my.cnf
            #- ./example/sql/v2/my.cnf:/root/.my.cnf

    cli:
        image: anax/dev
        volumes: [ ".:/home/anax/repo" ]

    apache:
        image: anax/dev:apache
        volumes: [ ".:/home/anax/repo" ]
        ports: [ "11000:80" ]

    remserver:
        image: anax/dev:apache
        ports:
            - "8090:80"
        volumes: [ ".:/home/anax/repo" ]

    php81:
        image: anax/dev:php81
        volumes: [ ".:/home/anax/repo" ]

    php81-apache:
        image: anax/dev:php81-apache
        ports: [ "11081:80" ]
        volumes: [ ".:/home/anax/repo" ]

    php80:
        image: anax/dev:php80
        volumes: [ ".:/home/anax/repo" ]

    php80-apache:
        image: anax/dev:php80-apache
        ports: [ "11080:80" ]
        volumes: [ ".:/home/anax/repo" ]

    php74:
        image: anax/dev:php74
        volumes: [ ".:/home/anax/repo" ]

    php74-apache:
        image: anax/dev:php74-apache
        ports: [ "11074:80" ]
        volumes: [ ".:/home/anax/repo" ]

    php73:
        image: anax/dev:php73
        volumes: [ ".:/home/anax/repo" ]

    php73-apache:
        image: anax/dev:php73-apache
        ports: [ "11073:80" ]
        volumes: [ ".:/home/anax/repo" ]

    php72:
        image: anax/dev:php72
        volumes: [ ".:/home/anax/repo" ]

    php72-apache:
        image: anax/dev:php72-apache
        ports: [ "11072:80" ]
        volumes: [ ".:/home/anax/repo" ]

    php71:
        image: anax/dev:php71
        volumes: [ ".:/home/anax/repo" ]

    php71-apache:
        image: anax/dev:php71-apache
        ports: [ "11071:80" ]
        volumes: [ ".:/home/anax/repo" ]

    php70:
        image: anax/dev:php70
        volumes: [ ".:/home/anax/repo" ]

    php70:
        image: anax/dev:php70-apache
        ports: [ "11070:80" ]
        volumes: [ ".:/home/anax/repo" ]

    php56:
        image: anax/dev:php56
        volumes: [ ".:/home/anax/repo" ]

    php56:
        image: anax/dev:php56-apache
        ports: [ "11056:80" ]
        volumes: [ ".:/home/anax/repo" ]
